name: fudex
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  bot_toast:
  cached_network_image:

  cupertino_icons:
  equatable:
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_screenutil:
  flutter_svg:
  get_it:
  google_fonts:
  injectable:
  logger:
  rxdart:
  shimmer:
  url_launcher:
  lottie: ^2.7.0
  file_picker: ^6.1.1
  intl: 
  permission_handler: ^11.2.0
  image_picker:
  image_cropper:
  flutter_animate: ^4.5.0
  rename: ^3.0.2
  dotted_border: ^2.1.0
  dotted_line: ^3.2.3
  dartz: ^0.10.1

dev_dependencies:
  build_runner:
  injectable_generator:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/data/

